---
- name: Copy update-host script
  become: yes
  template:
    src: update-hosts.sh.j2
    dest: /usr/sbin/update-hosts
    mode: 0744

- name: Creates a cron file under /etc/cron.d
  become: yes
  cron:
    name: update hosts
    minute: "*/10"
    user: root
    job: "/usr/sbin/update-hosts"
    cron_file: ansible_update_hosts
